export const MODAL_OPEN = "MODAL_OPEN";

export const EMPLOYEE_SELECTED = "EMPLOYEE_SELECTED";

export const EMPLOYEE_FETCH_REQUESTED = "EMPLOYEE_FETCH_REQUESTED";
export const EMPLOYEE_FETCH_SUCCEEDED = "EMPLOYEE_FETCH_SUCCEEDED";
export const EMPLOYEE_FETCH_FAILED = "EMPLOYEE_FETCH_FAILED";

export const EMPLOYEE_ADD_REQUESTED = "EMPLOYEE_ADD_REQUESTED";
export const EMPLOYEE_ADD_SUCCEEDED = "EMPLOYEE_ADD_SUCCEEDED";
export const EMPLOYEE_ADD_FAILED = "EMPLOYEE_ADD_FAILED";

export const EMPLOYEE_UPDATE_REQUESTED = "EMPLOYEE_UPDATE_REQUESTED";
export const EMPLOYEE_UPDATE_SUCCEEDED = "EMPLOYEE_UPDATE_SUCCEEDED";
export const EMPLOYEE_UPDATE_FAILED = "EMPLOYEE_UPDATE_FAILED";

export const EMPLOYEE_DELETE_REQUESTED = "EMPLOYEE_DELETE_REQUESTED";
export const EMPLOYEE_DELETE_SUCCEEDED = "EMPLOYEE_DELETE_SUCCEEDED";
export const EMPLOYEE_DELETE_FAILED = "EMPLOYEE_DELETE_FAILED";

export const BOT_SELECTED = "BOT_SELECTED";

export const BOT_FETCH_REQUESTED = "BOT_FETCH_REQUESTED";
export const BOT_FETCH_SUCCEEDED = "BOT_FETCH_SUCCEEDED";
export const BOT_FETCH_FAILED = "BOT_FETCH_FAILED";

export const BOT_ADD_REQUESTED = "BOT_ADD_REQUESTED";
export const BOT_ADD_SUCCEEDED = "BOT_ADD_SUCCEEDED";
export const BOT_ADD_FAILED = "BOT_ADD_FAILED";

export const BOT_UPDATE_REQUESTED = "BOT_UPDATE_REQUESTED";
export const BOT_UPDATE_SUCCEEDED = "BOT_UPDATE_SUCCEEDED";
export const BOT_UPDATE_FAILED = "BOT_UPDATE_FAILED";

export const BOT_DELETE_REQUESTED = "BOT_DELETE_REQUESTED";
export const BOT_DELETE_SUCCEEDED = "BOT_DELETE_SUCCEEDED";
export const BOT_DELETE_FAILED = "BOT_DELETE_FAILED";
